export const GET_DIMENSION_MEASURE_DATA = "GET_DIMENSION_MEASURE_DATA";
export const GET_PLOTTER_DATA = "GET_PLOTTER_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";
export const GET_PLOTTER_DATA_SUCCESS = "GET_PLOTTER_DATA_SUCCESS";
export const GET_PLOTTER_DATA_FAIL = "GET_PLOTTER_DATA_FAIL";
